# Generated by Django 6.0.2 on 2026-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='property_name',
            new_name='property_name_en',
        ),
        migrations.RenameField(
            model_name='renttype',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='rent',
            name='property_name_ar',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='renttype',
            name='name_ar',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
