# Generated by Codex on 2026-04-19

from django.db import migrations, models


def backfill_lease_details(apps, schema_editor):
    Rent = apps.get_model("rents", "Rent")
    for rent in Rent.objects.all().only("id", "start_date", "amount", "lease_start_date", "annual_rent_value"):
        update_fields = []
        if rent.start_date and rent.lease_start_date is None:
            rent.lease_start_date = rent.start_date
            update_fields.append("lease_start_date")
        if rent.amount is not None and rent.annual_rent_value is None:
            rent.annual_rent_value = rent.amount
            update_fields.append("annual_rent_value")
        if update_fields:
            rent.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("rents", "0003_rent_company_renttype_company_alter_renttype_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rent",
            name="annual_rent_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="auto_renewal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rent",
            name="lease_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="lease_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="notice",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="payment_schedule",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="rent",
            name="payments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="rent",
            name="security_deposit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(backfill_lease_details, migrations.RunPython.noop),
    ]
