# Generated by Codex on 2026-04-19

from decimal import Decimal, InvalidOperation

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def backfill_rent_payments(apps, schema_editor):
    Rent = apps.get_model("rents", "Rent")
    RentPayment = apps.get_model("rents", "RentPayment")

    for rent in Rent.objects.filter(is_active=True).exclude(payments="").only(
        "id",
        "payments",
        "lease_end_date",
        "one_time_due_date",
        "annual_rent_value",
    ):
        raw_amount = (rent.payments or "").strip().replace(",", "")
        if not raw_amount:
            continue
        try:
            amount = Decimal(raw_amount)
        except (InvalidOperation, ValueError):
            amount = rent.annual_rent_value or Decimal("0.00")

        if RentPayment.objects.filter(rent_id=rent.id, payment_number=1, is_active=True).exists():
            continue

        RentPayment.objects.create(
            rent_id=rent.id,
            payment_number=1,
            category="rent",
            status="paid",
            amount=amount,
            due_date=rent.lease_end_date or rent.one_time_due_date,
            paid_date=rent.lease_end_date or rent.one_time_due_date,
            notes="Imported from legacy payments field.",
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rents", "0004_rent_lease_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_number", models.PositiveSmallIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("rent", "Rent"),
                            ("security_deposit", "Security Deposit"),
                            ("other", "Other"),
                        ],
                        default="rent",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid"), ("cancelled", "Cancelled")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rent_payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="rents.rent",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rent_payments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["payment_number", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="rentpayment",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True),
                fields=("rent", "payment_number"),
                name="uniq_active_rent_payment_number",
            ),
        ),
        migrations.AddIndex(
            model_name="rentpayment",
            index=models.Index(fields=["rent", "is_active"], name="rents_payment_rent_active_idx"),
        ),
        migrations.AddIndex(
            model_name="rentpayment",
            index=models.Index(fields=["status", "category"], name="rents_payment_status_cat_idx"),
        ),
        migrations.RunPython(backfill_rent_payments, migrations.RunPython.noop),
    ]
