# Generated by Django 5.2.10 on 2026-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(db_index=True, max_length=254)),
                ("ip_address", models.CharField(db_index=True, max_length=45)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("first_failed_at", models.DateTimeField(auto_now_add=True)),
                ("last_failed_at", models.DateTimeField(auto_now=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["email", "ip_address"], name="accounts_lo_email_8d3c0f_idx")],
                "unique_together": {("email", "ip_address")},
            },
        ),
    ]
