# Generated by Django 5.2.10 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_accounts_lo_email_8d3c0f_idx_accounts_lo_email_b0d539_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_token_version",
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
    ]
