# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_organization(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    head_office, _ = OrganizationNode.objects.get_or_create(
        code="HEAD_OFFICE",
        defaults={
            "name": "Main Head Office",
            "node_type": "head_office",
            "employee_id_prefix": "",
            "is_active": True,
        },
    )
    for code, name, prefix in [
        ("FFI", "FFI", "FFI"),
        ("ASECO_PRO", "Aseco Pro", "ASECO"),
        ("ATHROYA", "Athroya", "ATH"),
    ]:
        OrganizationNode.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "node_type": "company",
                "parent_id": head_office.id,
                "employee_id_prefix": prefix,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('node_type', models.CharField(choices=[('head_office', 'Head Office'), ('company', 'Company')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_id_prefix', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.organizationnode')),
            ],
            options={
                'ordering': ['node_type', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserOrganizationAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access_entries', to='organization.organizationnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_access_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'organization_id'],
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.RunPython(seed_default_organization, migrations.RunPython.noop),
    ]
