# Generated by Django 6.0.2 on 2026-09-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationnode_late_notice_signer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationnode',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organizationnode',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
