# Generated by Django 6.0.2 on 2026-02-22 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import employees.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0007_backfill_hr_aligned_employee_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCodeSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prefix", models.CharField(max_length=3, unique=True)),
                ("value", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["prefix"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset_code", models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("VEHICLE", "Vehicle"), ("LAPTOP", "Laptop"), ("OTHER", "Other")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ASSIGNED", "Assigned"),
                            ("UNDER_MAINTENANCE", "Under Maintenance"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("asset_value", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=employees.storage.PrivateUploadStorage(),
                        upload_to="assets/invoices/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("flexible_attributes", models.JSONField(blank=True, null=True)),
                ("plate_number", models.CharField(blank=True, max_length=50)),
                ("chassis_number", models.CharField(blank=True, max_length=100)),
                ("engine_number", models.CharField(blank=True, max_length=100)),
                ("fuel_type", models.CharField(blank=True, max_length=50)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("registration_expiry", models.DateField(blank=True, null=True)),
                ("cpu", models.CharField(blank=True, max_length=100)),
                ("ram", models.CharField(blank=True, max_length=50)),
                ("storage", models.CharField(blank=True, max_length=50)),
                ("mac_address", models.CharField(blank=True, max_length=100)),
                ("operating_system", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "type"], name="assets_asset_status_type_idx"),
                    models.Index(fields=["warranty_expiry"], name="assets_asset_warranty_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetDamageReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="damage_reports", to="assets.asset"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_damage_reports",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("return_note", models.TextField(blank=True)),
                ("condition_on_return", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="assets.asset"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(fields=["employee", "is_active"], name="assets_asg_emp_active_idx"),
                    models.Index(fields=["asset", "is_active"], name="assets_asg_asset_active_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("asset",),
                        name="unique_active_assignment_per_asset",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetReturnRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PROCESSED", "Processed"), ("REJECTED", "Rejected")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="return_requests", to="assets.asset"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_return_requests",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_asset_return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [models.Index(fields=["status", "requested_at"], name="assets_ret_req_status_idx")],
            },
        ),
    ]
