# Generated by Django 6.0.2 on 2026-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='asset',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
