# Generated by Django 6.0.2 on 2026-03-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_rename_name_asset_name_en_asset_name_ar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assetdamagereport",
            name="ceo_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetdamagereport",
            name="ceo_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ceo_decided_asset_damage_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetdamagereport",
            name="ceo_decision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetdamagereport",
            name="hr_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetdamagereport",
            name="hr_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_decided_asset_damage_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetdamagereport",
            name="hr_decision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetdamagereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_HR", "Pending HR"),
                    ("PENDING_CEO", "Pending CEO"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING_HR",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="assetdamagereport",
            name="resolved",
        ),
        migrations.RemoveField(
            model_name="assetdamagereport",
            name="resolution_note",
        ),
        migrations.AddField(
            model_name="assetreturnrequest",
            name="ceo_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetreturnrequest",
            name="ceo_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ceo_decided_asset_return_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetreturnrequest",
            name="ceo_decision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetreturnrequest",
            name="hr_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetreturnrequest",
            name="hr_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_decided_asset_return_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetreturnrequest",
            name="hr_decision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="assetreturnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PENDING_CEO", "Pending CEO"),
                    ("APPROVED", "Approved"),
                    ("PROCESSED", "Processed"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
