# Generated by Django 6.0.3 on 2026-04-08 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_request_ceo_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetreturnrequest',
            name='manager_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetreturnrequest',
            name='manager_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_decided_asset_return_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturnrequest',
            name='manager_decision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetreturnrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager'), ('PENDING', 'Pending'), ('PENDING_CEO', 'Pending CEO'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
