# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_asset_company(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    Asset = apps.get_model("assets", "Asset")
    ffi = OrganizationNode.objects.get(code="FFI")
    Asset.objects.filter(company__isnull=True).update(company=ffi)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetreturnrequest_manager_decision_at_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organization.organizationnode'),
        ),
        migrations.RunPython(backfill_asset_company, migrations.RunPython.noop),
    ]
