# Generated by Django 6.0.3 on 2026-08-22 13:42

import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

ROLE_TITLES = {
    "HRManager": "HR Manager",
    "SystemAdmin": "System Administrator",
    "Manager": "Manager",
    "CEO": "Chief Executive Officer",
    "CFO": "Chief Financial Officer",
}


def _company_code(company) -> str:
    code = re.sub(r"[^A-Z0-9]+", "-", (company.code or "").upper()).strip("-")
    return code or str(company.pk)


def backfill_references_and_signers(apps, schema_editor):
    JobOffer = apps.get_model("job_offers", "JobOffer")
    EmployeeProfile = apps.get_model("employees", "EmployeeProfile")
    Position = apps.get_model("hr_reference", "Position")
    user_app, user_model = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app, user_model)

    next_sequences = {}
    blank_offers = JobOffer.objects.filter(models.Q(reference_number="") | models.Q(reference_number__isnull=True))
    for offer in blank_offers.select_related("company").order_by("company_id", "offer_date", "id").iterator():
        year = offer.offer_date.year
        prefix = f"JO-{_company_code(offer.company)}-{year}-"
        key = (offer.company_id, year)
        if key not in next_sequences:
            highest = 0
            references = JobOffer.objects.filter(
                company_id=offer.company_id,
                reference_number__startswith=prefix,
            ).values_list("reference_number", flat=True)
            for reference in references:
                suffix = reference.removeprefix(prefix)
                if suffix.isdigit():
                    highest = max(highest, int(suffix))
            next_sequences[key] = highest

        while True:
            next_sequences[key] += 1
            reference = f"{prefix}{next_sequences[key]:04d}"
            if not JobOffer.objects.filter(company_id=offer.company_id, reference_number=reference).exists():
                break
        JobOffer.objects.filter(pk=offer.pk).update(reference_number=reference)

    for offer in JobOffer.objects.all().iterator():
        user = User.objects.get(pk=offer.created_by_id)
        signer_name = (getattr(user, "full_name", "") or getattr(user, "email", "") or "").strip()
        profile = (
            EmployeeProfile.objects.filter(user_id=user.pk)
            .values(
                "job_title",
                "job_title_en",
                "position_ref_id",
            )
            .first()
        )
        signer_title = ""
        if profile:
            signer_title = (profile["job_title"] or profile["job_title_en"] or "").strip()
            if not signer_title and profile["position_ref_id"]:
                signer_title = (
                    Position.objects.filter(pk=profile["position_ref_id"]).values_list("name", flat=True).first() or ""
                ).strip()
        if not signer_title:
            group_names = set(user.groups.values_list("name", flat=True))
            signer_title = next((label for group, label in ROLE_TITLES.items() if group in group_names), "")
        if not signer_title:
            signer_title = "System Administrator" if user.is_superuser else "HR Manager"

        JobOffer.objects.filter(pk=offer.pk).update(
            hr_signer_user_id=user.pk,
            hr_signer_name=signer_name,
            hr_signer_title=signer_title,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("job_offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="hr_signer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signed_job_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_references_and_signers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="joboffer",
            name="hr_signer_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signed_job_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="joboffer",
            name="grade",
        ),
    ]
