# Generated by Django 6.0.3 on 2026-08-22 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0014_alter_employeeprofile_employment_status"),
        ("invites", "0005_invite_employee_profile"),
        ("job_offers", "0002_automate_reference_and_signer"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="joboffer",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference_number", ""), _negated=True), name="job_offer_reference_not_blank"
            ),
        ),
    ]
