# Generated by Django 6.0.3 on 2026-08-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import employees.storage


class Migration(migrations.Migration):
    dependencies = [
        ("job_offers", "0003_joboffer_job_offer_reference_not_blank"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HiringRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_number", models.CharField(max_length=100)),
                ("candidate_full_name", models.CharField(max_length=255)),
                ("candidate_email", models.EmailField(blank=True, max_length=254)),
                ("candidate_phone_number", models.CharField(blank=True, max_length=32)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("proposed_salary", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "cv_file",
                    models.FileField(storage=employees.storage.PrivateUploadStorage(), upload_to="hiring_request_cvs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("converted", "Converted"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("ceo_decision_at", models.DateTimeField(blank=True, null=True)),
                ("ceo_decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ceo_decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_hiring_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hiring_requests",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_hiring_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_hires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_hiring_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="joboffer",
            name="hiring_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_offer",
                to="job_offers.hiringrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="hiringrequest",
            index=models.Index(fields=["company", "status"], name="job_offers__company_be4aa4_idx"),
        ),
        migrations.AddIndex(
            model_name="hiringrequest",
            index=models.Index(fields=["company", "created_at"], name="job_offers__company_3f2e1e_idx"),
        ),
        migrations.AddConstraint(
            model_name="hiringrequest",
            constraint=models.UniqueConstraint(
                fields=("company", "reference_number"), name="unique_hiring_request_reference_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="hiringrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference_number", ""), _negated=True), name="hiring_request_reference_not_blank"
            ),
        ),
        migrations.AddConstraint(
            model_name="hiringrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("proposed_salary__gte", 0)), name="hiring_request_salary_nonnegative"
            ),
        ),
    ]
