# Generated by Django 6.0.3 on 2026-08-22 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0007_attendancerecord_biotime_emp_code_and_more"),
        ("employees", "0014_alter_employeeprofile_employment_status"),
        ("job_offers", "0004_hiringrequest_joboffer_hiring_request_and_more"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartingWorkAcknowledgment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_number", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("generated", "Generated")], db_index=True, default="generated", max_length=16
                    ),
                ),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("generated_by_system", models.BooleanField(default=True)),
                (
                    "attendance_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="starting_work_acknowledgment",
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="starting_work_acknowledgments",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="starting_work_acknowledgment",
                        to="employees.employeedocument",
                    ),
                ),
                (
                    "employee_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="starting_work_acknowledgment",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "job_offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="starting_work_acknowledgments",
                        to="job_offers.joboffer",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at", "-id"],
                "indexes": [models.Index(fields=["company", "status", "generated_at"], name="swa_company_status_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "reference_number"), name="unique_swa_reference_company"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reference_number", ""), _negated=True), name="swa_reference_not_blank"
                    ),
                ],
            },
        ),
    ]
