# Generated by Django 6.0.3 on 2026-08-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr_reference", "0002_department_company_position_company_sponsor_company_and_more"),
        ("job_offers", "0005_startingworkacknowledgment"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="department_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_offers",
                to="hr_reference.department",
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="position_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_offers",
                to="hr_reference.position",
            ),
        ),
    ]
