# Generated by Django 5.2.10 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("admin_portal", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="geofence_attendance_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
