# Generated by Django 6.0.2 on 2026-09-13 15:03

import datetime

from django.db import migrations, models


def initialize_canonical_grace_window(apps, schema_editor):
    """Preserve the legacy schedule value when introducing its canonical alias."""
    SystemSettings = apps.get_model("admin_portal", "SystemSettings")
    SystemSettings.objects.update(grace_window_minutes=models.F("late_grace_minutes"))


class Migration(migrations.Migration):
    dependencies = [
        ("admin_portal", "0003_systemsettings_attendance_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="approved_late_permission_limit_per_month",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="default_shift_end_time",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="during_shift_permission_max_minutes",
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="grace_use_limit_per_month",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="grace_window_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="permission_request_advance_limit_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="post_grace_tolerance_minutes",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.RunPython(initialize_canonical_grace_window, migrations.RunPython.noop),
    ]
