# Generated by Django 6.0.2 on 2026-09-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_systemsettings_approved_late_permission_limit_per_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='grace_use_limit_per_month',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='work_week_days',
        ),
    ]
