# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_reference_company(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    Department = apps.get_model("hr_reference", "Department")
    Position = apps.get_model("hr_reference", "Position")
    Sponsor = apps.get_model("hr_reference", "Sponsor")
    TaskGroup = apps.get_model("hr_reference", "TaskGroup")
    ffi = OrganizationNode.objects.get(code="FFI")
    Department.objects.filter(company__isnull=True).update(company=ffi)
    Position.objects.filter(company__isnull=True).update(company=ffi)
    Sponsor.objects.filter(company__isnull=True).update(company=ffi)
    TaskGroup.objects.filter(company__isnull=True).update(company=ffi)


class Migration(migrations.Migration):

    dependencies = [
        ('hr_reference', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.organizationnode'),
        ),
        migrations.AddField(
            model_name='position',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.organizationnode'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.organizationnode'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='organization.organizationnode'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(backfill_reference_company, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_department_company_code'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_position_company_code'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_sponsor_company_code'),
        ),
        migrations.AddConstraint(
            model_name='taskgroup',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_task_group_company_code'),
        ),
    ]
