# Generated by Django 5.2.10 on 2026-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
