# Generated by Django 6.0.2 on 2026-03-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_attendancerecord_manager_decision_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="ceo_decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="ceo_decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ceo_decided_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="ceo_decision_note",
            field=models.TextField(blank=True, help_text="CEO's decision note."),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_MGR", "Pending Manager"),
                    ("PENDING_HR", "Pending HR"),
                    ("PENDING_CEO", "Pending CEO"),
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("LATE", "Late"),
                    ("REJECTED", "Rejected"),
                    ("PENDING", "Pending (Legacy)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
