# Generated by Django 6.0.3 on 2026-03-31 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_ceo_stage_fields'),
        ('employees', '0008_employee_id_prefix_to_ffi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioTimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(help_text='IP address or domain of the BioTime server (e.g. 192.168.1.100)', max_length=100)),
                ('server_port', models.CharField(default='8090', help_text='Port for BioTime server (e.g. 8090)', max_length=10)),
                ('username', models.CharField(help_text='BioTime device/API username', max_length=100)),
                ('password', models.CharField(help_text='BioTime device/API password', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Enable/disable automatic syncing')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BioTime Configuration',
                'verbose_name_plural': 'BioTime Configuration',
            },
        ),
        migrations.CreateModel(
            name='BioTimeEmployeeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotime_emp_code', models.CharField(help_text='Employee code (ID) as set inside the ZKTeco BioTime device', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_mapping', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'BioTime Employee Mapping',
                'verbose_name_plural': 'BioTime Employee Mappings',
            },
        ),
    ]
