# Generated by Django 6.0.3 on 2026-05-16 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_biotimeconfig_biotimeemployeemap'),
        ('employees', '0010_employeedeletionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('requested_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('requested_status', models.CharField(blank=True, choices=[('PENDING_MGR', 'Pending Manager'), ('PENDING_HR', 'Pending HR'), ('PENDING_CEO', 'Pending CEO'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending (Legacy)')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_manager', 'Pending Manager'), ('pending_hr', 'Pending HR'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('manager_decision_at', models.DateTimeField(blank=True, null=True)),
                ('manager_decision_note', models.TextField(blank=True)),
                ('hr_decision_at', models.DateTimeField(blank=True, null=True)),
                ('hr_decision_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='attendance.attendancerecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_created', to=settings.AUTH_USER_MODEL)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_correction_requests', to='employees.employeeprofile')),
                ('hr_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_decided_attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('manager_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_decided_attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['employee_profile', 'date'], name='att_corr_emp_date_idx'), models.Index(fields=['status', 'created_at'], name='att_corr_status_created_idx')],
            },
        ),
    ]
