# Generated by Django 6.0.2 on 2026-08-12 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_attendancecorrectionrequest"),
        ("employees", "0011_employeedocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="biotime_emp_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="biotime_terminal_sn",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["date", "source", "status"], name="att_date_source_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="biotimeemployeemap",
            constraint=models.UniqueConstraint(
                fields=("employee_profile",), name="unique_biotime_mapping_per_employee"
            ),
        ),
    ]
