# Generated by Django 5.2.10 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0009_biotime_tenant_integrity"),
        ("organization", "0002_organizationscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("radius_meters", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_work_locations",
                        to="organization.organizationnode",
                    ),
                ),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.AddConstraint(
            model_name="worklocation",
            constraint=models.CheckConstraint(
                condition=Q(("latitude__gte", -90), ("latitude__lte", 90)), name="work_location_latitude_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="worklocation",
            constraint=models.CheckConstraint(
                condition=Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="work_location_longitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="worklocation",
            constraint=models.CheckConstraint(
                condition=Q(("radius_meters__gt", 0)), name="work_location_positive_radius"
            ),
        ),
        migrations.AddConstraint(
            model_name="worklocation",
            constraint=models.UniqueConstraint(
                condition=Q(("is_active", True)), fields=("company", "name"), name="unique_active_work_location_name"
            ),
        ),
    ]
