# Generated by Django 6.0.2 on 2026-09-13 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0012_retire_manual_attendance"),
        ("employees", "0025_employeeprofile_attendance_exempt"),
        ("organization", "0002_organizationscope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="is_biotime_projection",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="BioTimeRawPunch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attendance_date", models.DateField(db_index=True)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("biotime_emp_code", models.CharField(max_length=50)),
                ("provider_punch_id", models.CharField(blank=True, default="", max_length=128)),
                ("deduplication_key", models.CharField(editable=False, max_length=64, unique=True)),
                ("raw_punch_type", models.CharField(blank=True, default="", max_length=64)),
                ("terminal_sn", models.CharField(blank=True, default="", max_length=100)),
                ("provider_payload", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biotime_raw_punches",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biotime_raw_punches",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="NormalizedAttendanceEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attendance_date", models.DateField(db_index=True)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CHECK_IN", "Check in"),
                            ("CHECK_OUT", "Check out"),
                            ("BREAK_OUT", "Break out"),
                            ("BREAK_IN", "Break in"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("used_fallback", models.BooleanField(default=False)),
                ("normalized_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_attendance_events",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "raw_punch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_event",
                        to="attendance.biotimerawpunch",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("approved_minutes", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_adjustments",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_adjustments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_adjustments",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
                "indexes": [models.Index(fields=["employee_profile", "date"], name="att_adjustment_day_idx")],
            },
        ),
        migrations.CreateModel(
            name="AttendanceDailyResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("shift_start_at", models.DateTimeField()),
                ("shift_end_at", models.DateTimeField()),
                ("scheduled_minutes", models.PositiveIntegerField(default=0)),
                ("first_check_in_at", models.DateTimeField(blank=True, null=True)),
                ("final_check_out_at", models.DateTimeField(blank=True, null=True)),
                ("physical_work_minutes", models.PositiveIntegerField(default=0)),
                ("unpaid_break_minutes", models.PositiveIntegerField(default=0)),
                ("approved_permission_minutes", models.PositiveIntegerField(default=0)),
                ("accounted_attendance_minutes", models.PositiveIntegerField(default=0)),
                ("missing_minutes", models.PositiveIntegerField(default=0)),
                ("status_input", models.CharField(default="PRESENT", max_length=20)),
                ("calculation_inputs", models.JSONField(default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_daily_results",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_daily_results",
                        to="employees.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [models.Index(fields=["company", "date"], name="att_result_company_day_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("employee_profile", "date"), name="unique_attendance_daily_result")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="biotimerawpunch",
            index=models.Index(fields=["employee_profile", "attendance_date", "occurred_at"], name="raw_punch_day_idx"),
        ),
        migrations.AddIndex(
            model_name="biotimerawpunch",
            index=models.Index(fields=["company", "attendance_date"], name="raw_punch_company_day_idx"),
        ),
        migrations.AddIndex(
            model_name="normalizedattendanceevent",
            index=models.Index(fields=["employee_profile", "attendance_date"], name="norm_event_day_idx"),
        ),
        migrations.AddConstraint(
            model_name="normalizedattendanceevent",
            constraint=models.UniqueConstraint(
                fields=("employee_profile", "attendance_date", "sequence"), name="unique_normalized_attendance_sequence"
            ),
        ),
    ]
