# Generated by Django 6.0.2 on 2026-09-13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0013_attendancerecord_is_biotime_projection_and_more"),
        ("employees", "0025_employeeprofile_attendance_exempt"),
        ("organization", "0002_organizationscope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceadjustment", name="effective_date", field=models.DateField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="attendanceadjustment", name="end_time", field=models.TimeField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name="attendanceadjustment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("late_permission", "Late Permission"),
                    ("during_shift_permission", "During Shift Permission"),
                    ("exit_permission", "Exit Permission"),
                ],
                default="exit_permission",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="attendanceadjustment",
            name="source_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="attendanceadjustment", name="start_time", field=models.TimeField(blank=True, null=True)
        ),
        migrations.AddIndex(
            model_name="attendanceadjustment",
            index=models.Index(fields=["kind", "source_key"], name="att_adjustment_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="attendanceadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key", ""), _negated=True),
                fields=("kind", "source_key"),
                name="unique_att_adjustment_source",
            ),
        ),
    ]
