# Generated by Django 6.0.2 on 2026-09-14 04:56

import django.db.models.deletion
from django.db import migrations, models

import attendance.models
import employees.storage


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendancegraceuse_attendancelateviolation'),
        ('employees', '0025_employeeprofile_attendance_exempt'),
        ('in_app_notifications', '0002_notificationdelivery'),
        ('organization', '0003_organizationnode_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLateNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=64, unique=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('occurrence_number', models.PositiveIntegerField()),
                ('template_name', models.CharField(max_length=128)),
                ('template_version', models.PositiveIntegerField()),
                ('penalty_percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_logo_configured', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, storage=employees.storage.PrivateUploadStorage(), upload_to=attendance.models.attendance_late_notice_upload_to)),
                ('delivery_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=16)),
                ('delivery_message', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_late_notices', to='organization.organizationnode')),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_late_notices', to='employees.employeeprofile')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_late_notices', to='in_app_notifications.notification')),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='late_notice', to='attendance.attendancelateviolation')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['company', '-issued_at'], name='att_notice_company_idx'), models.Index(fields=['employee_profile', '-issued_at'], name='att_notice_employee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 4)), name='att_late_notice_level_range')],
            },
        ),
    ]
