# Generated by Django 6.0.2 on 2026-09-10 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0024_employeedocument_deletion_state"),
        ("organization", "0002_organizationscope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_no", models.CharField(max_length=32, unique=True)),
                ("request_date", models.DateField()),
                ("from_time", models.TimeField()),
                ("to_time", models.TimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                (
                    "exit_type",
                    models.CharField(
                        choices=[("business", "Business"), ("personal", "Personal"), ("emergency", "Emergency")],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_manager", "Pending Manager"),
                            ("pending_hr", "Pending HR"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_manager",
                        max_length=20,
                    ),
                ),
                (
                    "manager_decision",
                    models.CharField(
                        blank=True,
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("manager_decision_at", models.DateTimeField(blank=True, null=True)),
                ("manager_decision_note", models.TextField(blank=True)),
                (
                    "hr_decision",
                    models.CharField(
                        blank=True,
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("hr_decision_at", models.DateTimeField(blank=True, null=True)),
                ("hr_decision_note", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permission_requests",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_requests",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "hr_decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_decided_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager_decision_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_decided_permission_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["company", "employee", "request_date"], name="perm_req_co_emp_date_idx"),
                    models.Index(fields=["company", "status"], name="perm_req_co_status_idx"),
                    models.Index(fields=["company", "created_at"], name="perm_req_co_created_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending_manager", "pending_hr", "approved"])),
                        fields=("employee", "request_date"),
                        name="perm_req_one_active_per_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("to_time__gt", models.F("from_time"))), name="perm_req_to_after_from"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duration_minutes__gte", 1), ("duration_minutes__lte", 120)),
                        name="perm_req_duration_range",
                    ),
                ],
            },
        ),
    ]
