# Generated by Django 6.0.2 on 2026-09-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import employees.storage


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0014_attendanceadjustment_effective_date_and_more"),
        ("employees", "0025_employeeprofile_attendance_exempt"),
        ("organization", "0002_organizationscope"),
        ("permission_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionRequestAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        storage=employees.storage.PrivateUploadStorage(), upload_to="permission_request_evidence/"
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("capture_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.RemoveConstraint(model_name="permissionrequest", name="perm_req_one_active_per_day"),
        migrations.RemoveConstraint(model_name="permissionrequest", name="perm_req_duration_range"),
        migrations.AddField(
            model_name="permissionrequest",
            name="permission_type",
            field=models.CharField(
                choices=[("exit", "Exit"), ("late", "Late"), ("during_shift", "During shift")],
                default="exit",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest", name="duration_minutes", field=models.PositiveSmallIntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="exit_type",
            field=models.CharField(
                blank=True,
                choices=[("business", "Business"), ("personal", "Personal"), ("emergency", "Emergency")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest", name="from_time", field=models.TimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="permissionrequest", name="to_time", field=models.TimeField(blank=True, null=True)
        ),
        migrations.AddIndex(
            model_name="permissionrequest",
            index=models.Index(
                fields=["employee", "request_date", "permission_type", "status"], name="perm_req_conflict_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gte", 0), ("duration_minutes__lte", 1440)),
                name="perm_req_duration_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="permissionrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("duration_minutes", 0),
                        ("from_time__isnull", True),
                        ("permission_type", "late"),
                        ("to_time__isnull", True),
                    ),
                    models.Q(
                        ("duration_minutes__gte", 1),
                        ("from_time__isnull", False),
                        ("permission_type__in", ["exit", "during_shift"]),
                        ("to_time__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="perm_req_type_time_shape",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequestattachment",
            name="permission_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="permission_requests.permissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequestattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_request_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="permissionrequestattachment",
            index=models.Index(fields=["permission_request", "created_at"], name="perm_attachment_req_idx"),
        ),
    ]
