# Generated by Django 6.0.2 on 2026-09-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attendance", "0016_attendancelatenotice"),
        ("employees", "0027_contract_decision_cancelled"),
        ("organization", "0005_organizationnode_address_organizationnode_email_and_more"),
        ("payroll", "0006_attendancepayrolldeduction_claim_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PenaltyCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=8, unique=True)),
                ("category", models.CharField(max_length=24)),
                ("recurrence_group", models.CharField(max_length=24)),
                ("title_en", models.TextField()),
                ("title_ar", models.TextField()),
                ("description_en", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                (
                    "count_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("contract_year", "Contract year"),
                            ("cumulative", "Cumulative"),
                        ],
                        max_length=24,
                    ),
                ),
                ("levels", models.JSONField(default=list)),
                ("source_page", models.PositiveSmallIntegerField()),
                ("source_row", models.PositiveSmallIntegerField()),
                ("automatic", models.BooleanField(default=False)),
                ("extra_wage_deduction", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "ordering": ["category", "source_row"],
                "constraints": [
                    models.UniqueConstraint(fields=("category", "source_row"), name="unique_penalty_source_row")
                ],
            },
        ),
        migrations.CreateModel(
            name="PenaltyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("occurred_on", models.DateField()),
                ("occurrence_number", models.PositiveIntegerField()),
                ("action", models.CharField(max_length=40)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_hr_mark", "Pending HR mark"),
                            ("issued", "Issued"),
                            ("disputed", "Disputed"),
                            ("waived", "Waived"),
                            ("applied", "Applied"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "source",
                    models.CharField(choices=[("automatic", "Automatic attendance"), ("hr", "HR")], max_length=16),
                ),
                ("source_kind", models.CharField(blank=True, max_length=24)),
                ("note", models.TextField(blank=True)),
                ("employee_response", models.JSONField(blank=True, null=True)),
                ("resolution", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "attendance_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attendance.attendancedailyresult",
                    ),
                ),
                (
                    "catalog",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="penalties.penaltycatalog"),
                ),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organization.organizationnode"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="employees.employeeprofile"),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PenaltyDeduction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("intended_year", models.PositiveIntegerField()),
                ("intended_month", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("claimed_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("held", "Held"),
                            ("claimed", "Claimed by draft"),
                            ("applied", "Applied"),
                            ("void", "Void"),
                        ],
                        default="pending_review",
                        max_length=24,
                    ),
                ),
                ("review_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="organization.organizationnode"),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="employees.employeeprofile"),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="payroll.payrollrun"
                    ),
                ),
                (
                    "payroll_run_item",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="payroll.payrollrunitem"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "penalty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deduction",
                        to="penalties.penaltyrecord",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="penaltyrecord",
            index=models.Index(fields=["company", "occurred_on", "status"], name="penalty_company_date_status"),
        ),
        migrations.AddConstraint(
            model_name="penaltyrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attendance_result__isnull", False)),
                fields=("attendance_result", "source_kind"),
                name="unique_penalty_attendance_result_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="penaltyrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attendance_record__isnull", False)),
                fields=("attendance_record", "source_kind"),
                name="unique_penalty_attendance_record_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="penaltydeduction",
            index=models.Index(fields=["company", "status", "intended_year", "intended_month"], name="penalty_due_idx"),
        ),
    ]
