from django.db import migrations

CATALOG = [
    {
        "code": "W01",
        "category": "work_time",
        "recurrence_group": "W01",
        "title_en": "Arriving up to 15 minutes late without permission or acceptable excuse, without disrupting "
        "other workers",
        "title_ar": "التأخر عن مواعيد الحضور للعمل لغاية 15 دقيقة دون إذن أو عذر مقبول إذا لم يترتب على ذلك تعطيل "
        "عمال آخرين",
        "description_en": "Arriving up to 15 minutes late without permission or acceptable excuse, without "
        "disrupting other workers",
        "description_ar": "التأخر عن مواعيد الحضور للعمل لغاية 15 دقيقة دون إذن أو عذر مقبول إذا لم يترتب على ذلك "
        "تعطيل عمال آخرين",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "5"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "20"},
        ],
        "source_page": 39,
        "source_row": 1,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W02",
        "category": "work_time",
        "recurrence_group": "W02",
        "title_en": "Arriving up to 15 minutes late without permission or acceptable excuse, disrupting other workers",
        "title_ar": "التأخر عن مواعيد الحضور للعمل لغاية 15 دقيقة دون إذن أو عذر مقبول إذا ترتب على ذلك تعطيل عمال "
        "آخرين",
        "description_en": "Arriving up to 15 minutes late without permission or acceptable excuse, disrupting "
        "other workers",
        "description_ar": "التأخر عن مواعيد الحضور للعمل لغاية 15 دقيقة دون إذن أو عذر مقبول إذا ترتب على ذلك "
        "تعطيل عمال آخرين",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "15"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
        ],
        "source_page": 39,
        "source_row": 2,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W03",
        "category": "work_time",
        "recurrence_group": "W03",
        "title_en": "Arriving over 15 and up to 30 minutes late without permission or acceptable excuse, without "
        "disrupting other workers",
        "title_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 15 دقيقة لغاية 30 دقيقة دون إذن أو عذر مقبول إذا لم "
        "يترتب على ذلك تعطيل عمال آخرين",
        "description_en": "Arriving over 15 and up to 30 minutes late without permission or acceptable excuse, "
        "without disrupting other workers",
        "description_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 15 دقيقة لغاية 30 دقيقة دون إذن أو عذر مقبول إذا "
        "لم يترتب على ذلك تعطيل عمال آخرين",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "15"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
        ],
        "source_page": 39,
        "source_row": 3,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W04",
        "category": "work_time",
        "recurrence_group": "W04",
        "title_en": "Arriving over 15 and up to 30 minutes late without permission or acceptable excuse, "
        "disrupting other workers",
        "title_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 15 دقيقة لغاية 30 دقيقة دون إذن أو عذر مقبول إذا ترتب "
        "على ذلك تعطيل عمال آخرين",
        "description_en": "Arriving over 15 and up to 30 minutes late without permission or acceptable excuse, "
        "disrupting other workers",
        "description_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 15 دقيقة لغاية 30 دقيقة دون إذن أو عذر مقبول إذا "
        "ترتب على ذلك تعطيل عمال آخرين",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "75"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 39,
        "source_row": 4,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W05",
        "category": "work_time",
        "recurrence_group": "W05",
        "title_en": "Arriving over 30 and up to 60 minutes late without permission or acceptable excuse, without "
        "disrupting other workers",
        "title_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 30 دقيقة لغاية 60 دقيقة دون إذن أو عذر مقبول إذا لم "
        "يترتب على ذلك تعطيل عمال آخرين",
        "description_en": "Arriving over 30 and up to 60 minutes late without permission or acceptable excuse, "
        "without disrupting other workers",
        "description_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 30 دقيقة لغاية 60 دقيقة دون إذن أو عذر مقبول إذا "
        "لم يترتب على ذلك تعطيل عمال آخرين",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "75"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 39,
        "source_row": 5,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W06",
        "category": "work_time",
        "recurrence_group": "W06",
        "title_en": "Arriving over 30 and up to 60 minutes late without permission or acceptable excuse, "
        "disrupting other workers",
        "title_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 30 دقيقة لغاية 60 دقيقة دون إذن أو عذر مقبول إذا ترتب "
        "على ذلك تعطيل عمال آخرين",
        "description_en": "Arriving over 30 and up to 60 minutes late without permission or acceptable excuse, "
        "disrupting other workers",
        "description_ar": "التأخر عن مواعيد الحضور للعمل أكثر من 30 دقيقة لغاية 60 دقيقة دون إذن أو عذر مقبول إذا "
        "ترتب على ذلك تعطيل عمال آخرين",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "30"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
        ],
        "source_page": 39,
        "source_row": 6,
        "automatic": True,
        "extra_wage_deduction": "late_minutes",
    },
    {
        "code": "W07",
        "category": "work_time",
        "recurrence_group": "W07",
        "title_en": "Arriving more than 60 minutes late without permission or acceptable excuse, whether or not "
        "other workers are disrupted",
        "title_ar": "التأخر عن مواعيد الحضور للعمل لمدة تزيد على ساعة دون إذن أو عذر مقبول سواء ترتب أو لم يترتب "
        "على ذلك تعطيل عمال آخرين",
        "description_en": "Arriving more than 60 minutes late without permission or acceptable excuse, whether or "
        "not other workers are disrupted",
        "description_ar": "التأخر عن مواعيد الحضور للعمل لمدة تزيد على ساعة دون إذن أو عذر مقبول سواء ترتب أو لم "
        "يترتب على ذلك تعطيل عمال آخرين",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
        ],
        "source_page": 39,
        "source_row": 7,
        "automatic": True,
        "extra_wage_deduction": "late_hours",
    },
    {
        "code": "W08",
        "category": "work_time",
        "recurrence_group": "W08",
        "title_en": "Leaving work up to 15 minutes early without permission or acceptable excuse",
        "title_ar": "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما لا يتجاوز 15 دقيقة",
        "description_en": "Leaving work up to 15 minutes early without permission or acceptable excuse",
        "description_ar": "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما لا يتجاوز 15 دقيقة",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 39,
        "source_row": 8,
        "automatic": True,
        "extra_wage_deduction": "unworked_time",
    },
    {
        "code": "W09",
        "category": "work_time",
        "recurrence_group": "W09",
        "title_en": "Leaving work more than 15 minutes early without permission or acceptable excuse",
        "title_ar": "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما يتجاوز 15 دقيقة",
        "description_en": "Leaving work more than 15 minutes early without permission or acceptable excuse",
        "description_ar": "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما يتجاوز 15 دقيقة",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 39,
        "source_row": 9,
        "automatic": True,
        "extra_wage_deduction": "unworked_time",
    },
    {
        "code": "W10",
        "category": "work_time",
        "recurrence_group": "W10",
        "title_en": "Remaining at or returning to the workplace after work hours without prior permission",
        "title_ar": "البقاء في أماكن العمل أو العودة إليها بعد انتهاء مواعيد العمل دون إذن مسبق",
        "description_en": "Remaining at or returning to the workplace after work hours without prior permission",
        "description_ar": "البقاء في أماكن العمل أو العودة إليها بعد انتهاء مواعيد العمل دون إذن مسبق",
        "count_period": "monthly",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 39,
        "source_row": 10,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W11",
        "category": "work_time",
        "recurrence_group": "W11",
        "title_en": "Absent for one day without written permission or acceptable excuse within one contract year",
        "title_ar": "الغياب دون إذن كتابي أو عذر مقبول لمدة يوم خلال السنة العقدية الواحدة",
        "description_en": "Absent for one day without written permission or acceptable excuse within one contract year",
        "description_ar": "الغياب دون إذن كتابي أو عذر مقبول لمدة يوم خلال السنة العقدية الواحدة",
        "count_period": "contract_year",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
        ],
        "source_page": 40,
        "source_row": 11,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W12",
        "category": "work_time",
        "recurrence_group": "W12",
        "title_en": "Continuously absent for two to six days without written permission or acceptable excuse "
        "within one contract year",
        "title_ar": "الغياب المتصل دون إذن كتابي أو عذر مقبول من يومين إلى ستة أيام خلال السنة العقدية الواحدة",
        "description_en": "Continuously absent for two to six days without written permission or acceptable excuse "
        "within one contract year",
        "description_ar": "الغياب المتصل دون إذن كتابي أو عذر مقبول من يومين إلى ستة أيام خلال السنة العقدية الواحدة",
        "count_period": "contract_year",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "4"},
            {
                "occurrence": 4,
                "action": "promotion_delay_or_one_allowance_denial",
                "amount_basis": None,
                "amount_value": None,
            },
        ],
        "source_page": 40,
        "source_row": 12,
        "automatic": True,
        "extra_wage_deduction": "absence_period",
    },
    {
        "code": "W13",
        "category": "work_time",
        "recurrence_group": "W13",
        "title_en": "Continuously absent for seven to ten days without written permission or acceptable excuse "
        "within one contract year",
        "title_ar": "الغياب المتصل دون إذن كتابي أو عذر مقبول من سبعة أيام إلى عشرة أيام خلال السنة العقدية الواحدة",
        "description_en": "Continuously absent for seven to ten days without written permission or acceptable "
        "excuse within one contract year",
        "description_ar": "الغياب المتصل دون إذن كتابي أو عذر مقبول من سبعة أيام إلى عشرة أيام خلال السنة العقدية "
        "الواحدة",
        "count_period": "contract_year",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "4"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {
                "occurrence": 3,
                "action": "promotion_delay_or_one_allowance_denial",
                "amount_basis": None,
                "amount_value": None,
            },
            {
                "occurrence": 4,
                "action": "conditional_termination_with_benefit",
                "amount_basis": None,
                "amount_value": None,
            },
        ],
        "source_page": 40,
        "source_row": 13,
        "automatic": True,
        "extra_wage_deduction": "absence_period",
    },
    {
        "code": "W14",
        "category": "work_time",
        "recurrence_group": "W14",
        "title_en": "Continuously absent for eleven to fourteen days without written permission or acceptable "
        "excuse within one contract year",
        "title_ar": "الغياب المتصل دون إذن كتابي أو عذر مقبول من أحد عشر يوما إلى أربعة عشر يوما خلال السنة "
        "العقدية الواحدة",
        "description_en": "Continuously absent for eleven to fourteen days without written permission or "
        "acceptable excuse within one contract year",
        "description_ar": "الغياب المتصل دون إذن كتابي أو عذر مقبول من أحد عشر يوما إلى أربعة عشر يوما خلال السنة "
        "العقدية الواحدة",
        "count_period": "contract_year",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {
                "occurrence": 2,
                "action": "promotion_delay_or_one_allowance_denial_with_article_80_warning",
                "amount_basis": None,
                "amount_value": None,
            },
            {"occurrence": 3, "action": "article_80_termination", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 40,
        "source_row": 14,
        "automatic": True,
        "extra_wage_deduction": "absence_period",
    },
    {
        "code": "W15",
        "category": "work_time",
        "recurrence_group": "W15",
        "title_en": "Uninterrupted absence for more than fifteen days without a legitimate reason in one contract "
        "year; written warning after ten days required",
        "title_ar": "الانقطاع عن العمل دون سبب مشروع لمدة تزيد على خمسة عشر يوما متصلة خلال السنة العقدية الواحدة "
        "على أن يسبقه إنذار كتابي بعد الغياب مدة عشرة أيام",
        "description_en": "Uninterrupted absence for more than fifteen days without a legitimate reason in one "
        "contract year; written warning after ten days required",
        "description_ar": "الانقطاع عن العمل دون سبب مشروع لمدة تزيد على خمسة عشر يوما متصلة خلال السنة العقدية "
        "الواحدة على أن يسبقه إنذار كتابي بعد الغياب مدة عشرة أيام",
        "count_period": "contract_year",
        "levels": [{"occurrence": 1, "action": "article_80_termination", "amount_basis": None, "amount_value": None}],
        "source_page": 40,
        "source_row": 15,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "W16",
        "category": "work_time",
        "recurrence_group": "W16",
        "title_en": "Intermittent absence totalling more than thirty days without a legitimate reason in one "
        "contract year; written warning after twenty days required",
        "title_ar": "الغياب المتقطع دون سبب مشروع مدة تزيد في مجموعها على ثلاثين يوما خلال السنة العقدية الواحدة "
        "على أن يسبقه إنذار كتابي بعد الغياب مدة عشرين يوما",
        "description_en": "Intermittent absence totalling more than thirty days without a legitimate reason in one "
        "contract year; written warning after twenty days required",
        "description_ar": "الغياب المتقطع دون سبب مشروع مدة تزيد في مجموعها على ثلاثين يوما خلال السنة العقدية "
        "الواحدة على أن يسبقه إنذار كتابي بعد الغياب مدة عشرين يوما",
        "count_period": "contract_year",
        "levels": [{"occurrence": 1, "action": "article_80_termination", "amount_basis": None, "amount_value": None}],
        "source_page": 40,
        "source_row": 16,
        "automatic": True,
        "extra_wage_deduction": "",
    },
    {
        "code": "O01",
        "category": "work_organization",
        "recurrence_group": "O01",
        "title_en": "Being outside the assigned workplace during working hours without justification",
        "title_ar": "التواجد دون مبرر في غير مكان العمل المخصص للعامل أثناء وقت الدوام",
        "description_en": "Being outside the assigned workplace during working hours without justification",
        "description_ar": "التواجد دون مبرر في غير مكان العمل المخصص للعامل أثناء وقت الدوام",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 40,
        "source_row": 1,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O02",
        "category": "work_organization",
        "recurrence_group": "O02",
        "title_en": "Receiving visitors on work premises for matters unrelated to work without management permission",
        "title_ar": "استقبال زائرين في غير أمور عمل المنشأة في أماكن العمل دون إذن من الإدارة",
        "description_en": "Receiving visitors on work premises for matters unrelated to work without management "
        "permission",
        "description_ar": "استقبال زائرين في غير أمور عمل المنشأة في أماكن العمل دون إذن من الإدارة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "15"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
        ],
        "source_page": 40,
        "source_row": 2,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O03",
        "category": "work_organization",
        "recurrence_group": "O03",
        "title_en": "Using the establishment's machines, equipment or tools for private purposes without permission",
        "title_ar": "استعمال آلات ومعدات وأدوات المنشأة لأغراض خاصة دون إذن",
        "description_en": "Using the establishment's machines, equipment or tools for private purposes without "
        "permission",
        "description_ar": "استعمال آلات ومعدات وأدوات المنشأة لأغراض خاصة دون إذن",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
        ],
        "source_page": 40,
        "source_row": 3,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O04",
        "category": "work_organization",
        "recurrence_group": "O04",
        "title_en": "Interfering without authority in work outside the worker's duties",
        "title_ar": "تدخل العامل دون وجه حق في أي عمل ليس في اختصاصه أو لم يعهد به إليه",
        "description_en": "Interfering without authority in work outside the worker's duties",
        "description_ar": "تدخل العامل دون وجه حق في أي عمل ليس في اختصاصه أو لم يعهد به إليه",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
        ],
        "source_page": 40,
        "source_row": 4,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O05",
        "category": "work_organization",
        "recurrence_group": "O05",
        "title_en": "Entering or leaving through a place other than the designated entrance or exit",
        "title_ar": "الخروج أو الدخول من غير المكان المخصص لذلك",
        "description_en": "Entering or leaving through a place other than the designated entrance or exit",
        "description_ar": "الخروج أو الدخول من غير المكان المخصص لذلك",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "15"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
        ],
        "source_page": 41,
        "source_row": 5,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O06",
        "category": "work_organization",
        "recurrence_group": "O06",
        "title_en": "Neglecting to clean, maintain or care for machinery, or failing to report a fault",
        "title_ar": "الإهمال في تنظيف الآلات وصيانتها أو عدم العناية بها أو عدم التبليغ عما بها من خلل",
        "description_en": "Neglecting to clean, maintain or care for machinery, or failing to report a fault",
        "description_ar": "الإهمال في تنظيف الآلات وصيانتها أو عدم العناية بها أو عدم التبليغ عما بها من خلل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
        ],
        "source_page": 41,
        "source_row": 6,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O07",
        "category": "work_organization",
        "recurrence_group": "O07",
        "title_en": "Failing to put repair, maintenance or other tools in their designated places after work",
        "title_ar": "عدم وضع أدوات الإصلاح والصيانة واللوازم الأخرى في الأماكن المخصصة لها بعد الانتهاء من العمل",
        "description_en": "Failing to put repair, maintenance or other tools in their designated places after work",
        "description_ar": "عدم وضع أدوات الإصلاح والصيانة واللوازم الأخرى في الأماكن المخصصة لها بعد الانتهاء من العمل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 41,
        "source_row": 7,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O08",
        "category": "work_organization",
        "recurrence_group": "O08",
        "title_en": "Tearing or damaging establishment notices or management announcements",
        "title_ar": "تمزيق أو إتلاف إعلانات أو بلاغات إدارة المنشأة",
        "description_en": "Tearing or damaging establishment notices or management announcements",
        "description_ar": "تمزيق أو إتلاف إعلانات أو بلاغات إدارة المنشأة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 41,
        "source_row": 8,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O09",
        "category": "work_organization",
        "recurrence_group": "O09",
        "title_en": "Neglecting property entrusted to the worker, such as vehicles, machines, devices, equipment "
        "or tools",
        "title_ar": "الإهمال في العهد التي بحوزته مثل سيارات وآلات وأجهزة ومعدات وأدوات",
        "description_en": "Neglecting property entrusted to the worker, such as vehicles, machines, devices, "
        "equipment or tools",
        "description_ar": "الإهمال في العهد التي بحوزته مثل سيارات وآلات وأجهزة ومعدات وأدوات",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 41,
        "source_row": 9,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O10",
        "category": "work_organization",
        "recurrence_group": "O10",
        "title_en": "Eating in the workplace, an undesignated place, or outside rest times",
        "title_ar": "الأكل في مكان العمل أو غير المكان المعد له أو في غير أوقات الراحة",
        "description_en": "Eating in the workplace, an undesignated place, or outside rest times",
        "description_ar": "الأكل في مكان العمل أو غير المكان المعد له أو في غير أوقات الراحة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "15"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
        ],
        "source_page": 41,
        "source_row": 10,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O11",
        "category": "work_organization",
        "recurrence_group": "O11",
        "title_en": "Sleeping during work",
        "title_ar": "النوم أثناء العمل",
        "description_en": "Sleeping during work",
        "description_ar": "النوم أثناء العمل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
        ],
        "source_page": 41,
        "source_row": 11,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O12",
        "category": "work_organization",
        "recurrence_group": "O12",
        "title_en": "Sleeping in duties requiring constant vigilance",
        "title_ar": "النوم في الحالات التي تستدعي يقظة مستمرة",
        "description_en": "Sleeping in duties requiring constant vigilance",
        "description_ar": "النوم في الحالات التي تستدعي يقظة مستمرة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
        ],
        "source_page": 41,
        "source_row": 12,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O13",
        "category": "work_organization",
        "recurrence_group": "O13",
        "title_en": "Loitering or being away from one's work location during working hours",
        "title_ar": "التسكع أو وجود العامل في غير مكان عمله أثناء ساعات العمل",
        "description_en": "Loitering or being away from one's work location during working hours",
        "description_ar": "التسكع أو وجود العامل في غير مكان عمله أثناء ساعات العمل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
        ],
        "source_page": 41,
        "source_row": 13,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O14",
        "category": "work_organization",
        "recurrence_group": "O14",
        "title_en": "Manipulating attendance or departure records",
        "title_ar": "التلاعب في إثبات الحضور والانصراف",
        "description_en": "Manipulating attendance or departure records",
        "description_ar": "التلاعب في إثبات الحضور والانصراف",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {
                "occurrence": 3,
                "action": "promotion_delay_or_one_allowance_denial",
                "amount_basis": None,
                "amount_value": None,
            },
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 41,
        "source_row": 14,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O15",
        "category": "work_organization",
        "recurrence_group": "O15",
        "title_en": "Disobeying ordinary work orders or posted work instructions",
        "title_ar": "عدم إطاعة الأوامر العادية الخاصة بالعمل أو عدم تنفيذ التعليمات الخاصة بالعمل والمعلقة في مكان "
        "ظاهر",
        "description_en": "Disobeying ordinary work orders or posted work instructions",
        "description_ar": "عدم إطاعة الأوامر العادية الخاصة بالعمل أو عدم تنفيذ التعليمات الخاصة بالعمل والمعلقة "
        "في مكان ظاهر",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
        ],
        "source_page": 41,
        "source_row": 15,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O16",
        "category": "work_organization",
        "recurrence_group": "O16",
        "title_en": "Inciting violation of work orders or written work instructions",
        "title_ar": "التحريض على مخالفة الأوامر والتعليمات الخطية الخاصة بالعمل",
        "description_en": "Inciting violation of work orders or written work instructions",
        "description_ar": "التحريض على مخالفة الأوامر والتعليمات الخطية الخاصة بالعمل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 41,
        "source_row": 16,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O17",
        "category": "work_organization",
        "recurrence_group": "O17",
        "title_en": "Smoking in prohibited places posted for worker and establishment safety",
        "title_ar": "التدخين في الأماكن المحظورة والمعلن عنها للمحافظة على سلامة العمال والمنشأة",
        "description_en": "Smoking in prohibited places posted for worker and establishment safety",
        "description_ar": "التدخين في الأماكن المحظورة والمعلن عنها للمحافظة على سلامة العمال والمنشأة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 41,
        "source_row": 17,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "O18",
        "category": "work_organization",
        "recurrence_group": "O18",
        "title_en": "Negligence or carelessness at work that may harm workers' health or safety, materials, tools "
        "or equipment",
        "title_ar": "الإهمال أو التهاون في العمل الذي قد ينشأ عنه ضرر في صحة العمال أو سلامتهم أو في المواد أو "
        "الأدوات والأجهزة",
        "description_en": "Negligence or carelessness at work that may harm workers' health or safety, materials, "
        "tools or equipment",
        "description_ar": "الإهمال أو التهاون في العمل الذي قد ينشأ عنه ضرر في صحة العمال أو سلامتهم أو في المواد "
        "أو الأدوات والأجهزة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 41,
        "source_row": 18,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B01",
        "category": "worker_conduct",
        "recurrence_group": "B01",
        "title_en": "Quarrelling with colleagues or others, or causing disturbances at work",
        "title_ar": "التشاجر مع الزملاء أو مع الغير أو إحداث مشاغبات في مكان العمل",
        "description_en": "Quarrelling with colleagues or others, or causing disturbances at work",
        "description_ar": "التشاجر مع الزملاء أو مع الغير أو إحداث مشاغبات في مكان العمل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
        ],
        "source_page": 41,
        "source_row": 1,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B02",
        "category": "worker_conduct",
        "recurrence_group": "B02",
        "title_en": "Feigning illness or falsely claiming an injury during or because of work",
        "title_ar": "التمارض أو ادعاء العامل كذبا أنه أصيب أثناء العمل أو بسببه",
        "description_en": "Feigning illness or falsely claiming an injury during or because of work",
        "description_ar": "التمارض أو ادعاء العامل كذبا أنه أصيب أثناء العمل أو بسببه",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
        ],
        "source_page": 41,
        "source_row": 2,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B03",
        "category": "worker_conduct",
        "recurrence_group": "B03",
        "title_en": "Refusing a medical examination requested by the establishment doctor or treatment instructions",
        "title_ar": "الامتناع عن إجراء الكشف الطبي عند طلب طبيب المنشأة أو رفض اتباع التعليمات الطبية أثناء العلاج",
        "description_en": "Refusing a medical examination requested by the establishment doctor or treatment "
        "instructions",
        "description_ar": "الامتناع عن إجراء الكشف الطبي عند طلب طبيب المنشأة أو رفض اتباع التعليمات الطبية أثناء "
        "العلاج",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
        ],
        "source_page": 41,
        "source_row": 3,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B04",
        "category": "worker_conduct",
        "recurrence_group": "B04",
        "title_en": "Violating posted health instructions at the workplace",
        "title_ar": "مخالفة التعليمات الصحية المعلقة بأماكن العمل",
        "description_en": "Violating posted health instructions at the workplace",
        "description_ar": "مخالفة التعليمات الصحية المعلقة بأماكن العمل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
        ],
        "source_page": 42,
        "source_row": 4,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B05",
        "category": "worker_conduct",
        "recurrence_group": "B05",
        "title_en": "Writing on establishment walls or affixing notices to them",
        "title_ar": "الكتابة على جدران المنشأة أو لصق إعلانات عليها",
        "description_en": "Writing on establishment walls or affixing notices to them",
        "description_ar": "الكتابة على جدران المنشأة أو لصق إعلانات عليها",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "10"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
        ],
        "source_page": 42,
        "source_row": 5,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B06",
        "category": "worker_conduct",
        "recurrence_group": "B06",
        "title_en": "Refusing administrative inspection on departure",
        "title_ar": "رفض التفتيش الإداري عند الانصراف",
        "description_en": "Refusing administrative inspection on departure",
        "description_ar": "رفض التفتيش الإداري عند الانصراف",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "25"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": "50"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
        ],
        "source_page": 42,
        "source_row": 6,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B07",
        "category": "worker_conduct",
        "recurrence_group": "B07",
        "title_en": "Failing to hand over establishment collections on the specified dates without acceptable "
        "justification",
        "title_ar": "عدم تسليم النقود المحصلة لحساب المنشأة في المواعيد المحددة دون تبرير مقبول",
        "description_en": "Failing to hand over establishment collections on the specified dates without "
        "acceptable justification",
        "description_ar": "عدم تسليم النقود المحصلة لحساب المنشأة في المواعيد المحددة دون تبرير مقبول",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 42,
        "source_row": 7,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B08",
        "category": "worker_conduct",
        "recurrence_group": "B08",
        "title_en": "Refusing to wear required protective clothing or equipment",
        "title_ar": "الامتناع عن ارتداء الملابس والأجهزة المقررة للوقاية والسلامة",
        "description_en": "Refusing to wear required protective clothing or equipment",
        "description_ar": "الامتناع عن ارتداء الملابس والأجهزة المقررة للوقاية والسلامة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "written_warning", "amount_basis": None, "amount_value": None},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
        ],
        "source_page": 42,
        "source_row": 8,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B09",
        "category": "worker_conduct",
        "recurrence_group": "B09",
        "title_en": "Deliberate seclusion with a person of the opposite sex at work",
        "title_ar": "تعمد الخلوة مع الجنس الآخر في أماكن العمل",
        "description_en": "Deliberate seclusion with a person of the opposite sex at work",
        "description_ar": "تعمد الخلوة مع الجنس الآخر في أماكن العمل",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 42,
        "source_row": 9,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B10",
        "category": "worker_conduct",
        "recurrence_group": "B10",
        "title_en": "Offending others in a way that violates decency, by speech or action",
        "title_ar": "الإيحاء للآخرين بما يخدش الحياء قولا أو فعلا",
        "description_en": "Offending others in a way that violates decency, by speech or action",
        "description_ar": "الإيحاء للآخرين بما يخدش الحياء قولا أو فعلا",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 42,
        "source_row": 10,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B11",
        "category": "worker_conduct",
        "recurrence_group": "B11",
        "title_en": "Verbally assaulting colleagues by speech, gesture, abusive electronic communications or "
        "belittling",
        "title_ar": "الاعتداء على زملاء العمل بالقول أو الإشارة أو باستعمال وسائل الاتصال الإلكترونية بالشتم أو "
        "التحقير",
        "description_en": "Verbally assaulting colleagues by speech, gesture, abusive electronic communications or "
        "belittling",
        "description_ar": "الاعتداء على زملاء العمل بالقول أو الإشارة أو باستعمال وسائل الاتصال الإلكترونية بالشتم "
        "أو التحقير",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 42,
        "source_row": 11,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B12",
        "category": "worker_conduct",
        "recurrence_group": "B12",
        "title_en": "Physical assault on colleagues or others in an indecent manner",
        "title_ar": "الاعتداء بالإيذاء الجسدي على زملاء العمل أو على غيرهم بطريقة إباحية",
        "description_en": "Physical assault on colleagues or others in an indecent manner",
        "description_ar": "الاعتداء بالإيذاء الجسدي على زملاء العمل أو على غيرهم بطريقة إباحية",
        "count_period": "cumulative",
        "levels": [
            {
                "occurrence": 1,
                "action": "termination_without_benefit_or_notice_or_compensation",
                "amount_basis": None,
                "amount_value": None,
            }
        ],
        "source_page": 42,
        "source_row": 12,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B13",
        "category": "worker_conduct",
        "recurrence_group": "B13",
        "title_en": "Physical or verbal assault or abusive electronic communications against the employer, manager "
        "or superiors",
        "title_ar": "الاعتداء الجسدي أو القولي أو بأي وسيلة من وسائل الاتصال الإلكترونية على صاحب العمل أو المدير "
        "المسؤول أو أحد الرؤساء أثناء العمل أو بسببه",
        "description_en": "Physical or verbal assault or abusive electronic communications against the employer, "
        "manager or superiors",
        "description_ar": "الاعتداء الجسدي أو القولي أو بأي وسيلة من وسائل الاتصال الإلكترونية على صاحب العمل أو "
        "المدير المسؤول أو أحد الرؤساء أثناء العمل أو بسببه",
        "count_period": "cumulative",
        "levels": [
            {
                "occurrence": 1,
                "action": "termination_without_benefit_or_notice_or_compensation",
                "amount_basis": None,
                "amount_value": None,
            }
        ],
        "source_page": 42,
        "source_row": 13,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B14",
        "category": "worker_conduct",
        "recurrence_group": "B14",
        "title_en": "Submitting a malicious report or complaint",
        "title_ar": "تقديم بلاغ أو شكوى كيدية",
        "description_en": "Submitting a malicious report or complaint",
        "description_ar": "تقديم بلاغ أو شكوى كيدية",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 3, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 42,
        "source_row": 14,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B15",
        "category": "worker_conduct",
        "recurrence_group": "B15",
        "title_en": "Failing to comply with an investigation committee's request to attend",
        "title_ar": "عدم الامتثال لطلب لجنة التحقيق بالحضور",
        "description_en": "Failing to comply with an investigation committee's request to attend",
        "description_ar": "عدم الامتثال لطلب لجنة التحقيق بالحضور",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
            {"occurrence": 4, "action": "termination_with_benefit", "amount_basis": None, "amount_value": None},
        ],
        "source_page": 42,
        "source_row": 15,
        "automatic": False,
        "extra_wage_deduction": "",
    },
    {
        "code": "B16",
        "category": "worker_conduct",
        "recurrence_group": "B16",
        "title_en": "Failing to observe the establishment's approved official uniform",
        "title_ar": "عدم التقيد بالزي الرسمي المعتمد بالمنشأة",
        "description_en": "Failing to observe the establishment's approved official uniform",
        "description_ar": "عدم التقيد بالزي الرسمي المعتمد بالمنشأة",
        "count_period": "cumulative",
        "levels": [
            {"occurrence": 1, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "1"},
            {"occurrence": 2, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "2"},
            {"occurrence": 3, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "3"},
            {"occurrence": 4, "action": "deduction", "amount_basis": "daily_wage_days", "amount_value": "5"},
        ],
        "source_page": 42,
        "source_row": 16,
        "automatic": False,
        "extra_wage_deduction": "",
    },
]


def seed_catalog(apps, schema_editor):
    model = apps.get_model("penalties", "PenaltyCatalog")
    model.objects.bulk_create([model(**row) for row in CATALOG], ignore_conflicts=True)


def unseed_catalog(apps, schema_editor):
    # Catalog identities are protected historical reference data.
    # Keep them on rollback rather than deleting referenced rows.
    pass


class Migration(migrations.Migration):
    dependencies = [("penalties", "0001_initial")]
    operations = [migrations.RunPython(seed_catalog, unseed_catalog)]
