# Generated by Django 6.0.2 on 2026-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("penalties", "0002_seed_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="penaltyrecord",
            name="evidence",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="penaltyrecord",
            name="extra_wage_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="penaltyrecord",
            name="total_deduction_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
