# Generated by Django 6.0.2 on 2026-10-01 13:35

import django.db.models.deletion
from django.db import migrations, models

import employees.storage
import penalties.models


class Migration(migrations.Migration):
    # Depends only on committed migrations of the referenced apps.
    dependencies = [
        ("employees", "0027_contract_decision_cancelled"),
        ("in_app_notifications", "0002_notificationdelivery"),
        ("organization", "0005_organizationnode_address_organizationnode_email_and_more"),
        ("penalties", "0004_refresh_frozen_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="penaltyrecord",
            name="automation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("warning_pending", "Automatic warning pending"),
                    ("warning_issued", "Automatic warning issued"),
                ],
                db_index=True,
                default="",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="PenaltyWarningNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_number", models.CharField(max_length=64, unique=True)),
                ("template_name", models.CharField(max_length=128)),
                ("template_version", models.PositiveIntegerField()),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        storage=employees.storage.PrivateUploadStorage(),
                        upload_to=penalties.models.penalty_warning_notice_upload_to,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("delivery_message", models.CharField(blank=True, max_length=255)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalty_warning_notices",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalty_warning_notices",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="penalty_warning_notices",
                        to="in_app_notifications.notification",
                    ),
                ),
                (
                    "penalty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warning_notice",
                        to="penalties.penaltyrecord",
                    ),
                ),
            ],
        ),
    ]
