# Generated by Django 5.2.10 on 2026-01-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='allow_carry_over',
            field=models.BooleanField(default=False, help_text='If true, unused balance carries over to next year'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='annual_quota',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Annual quota in days (e.g. 21.0)', max_digits=5),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carry_over',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max days to carry over. If null, unlimited.', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='LeaveBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('used', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_snapshots', to='employees.employeeprofile')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='leaves.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Balance Snapshot',
                'verbose_name_plural': 'Leave Balance Snapshots',
                'constraints': [models.UniqueConstraint(fields=('employee_profile', 'leave_type', 'year'), name='unique_balance_snapshot')],
            },
        ),
    ]
