# Generated by Django 5.2.10 on 2026-01-22 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavetype_allow_carry_over_leavetype_annual_quota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='hr_decision_note',
            field=models.TextField(blank=True, help_text="HR's decision note."),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_decided_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_decision_note',
            field=models.TextField(blank=True, help_text="Manager's note."),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, help_text='Time of final (HR) decision.', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='HR user who made the final decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_decided_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='decision_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection or approval note (Legacy/HR).'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager Approval'), ('PENDING_HR', 'Pending HR Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_HR', max_length=20),
        ),
    ]
