# Generated by Django 5.2.10 on 2026-01-31 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0004_leave_request_status_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("pending_manager", "Pending Manager"),
                    ("pending_hr", "Pending HR"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeaveBalanceAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "adjustment_days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Number of days to add (positive) or deduct (negative).",
                        max_digits=5,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for adjustment.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_balance_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="The employee whose balance is adjusted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="adjustments", to="leaves.leavetype"
                    ),
                ),
            ],
        ),
    ]
