# Generated by Django 6.0.2 on 2026-02-16 13:50

from django.db import migrations, models

import employees.storage


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0005_alter_leaverequest_status_leavebalanceadjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Supporting document for leave request.",
                null=True,
                storage=employees.storage.PrivateUploadStorage(),
                upload_to="leave_documents/",
            ),
        ),
    ]
