# Generated by Django 6.0.2 on 2026-02-19 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leaverequest_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceo_decided_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='ceo_decision_note',
            field=models.TextField(blank=True, help_text="CEO's decision note."),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_ceo_approval',
            field=models.BooleanField(default=False, help_text='If true, requires CEO approval after HR.'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('pending_manager', 'Pending Manager'), ('pending_hr', 'Pending HR'), ('pending_ceo', 'Pending CEO'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=20),
        ),
    ]
