# Generated by Django 6.0.2 on 2026-03-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0007_leaverequest_ceo_decision_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="entered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="HR user who entered this record manually.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_entered_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="manual_entry_reason",
            field=models.TextField(blank=True, help_text="Reason entered by HR for manual records."),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="source",
            field=models.CharField(
                choices=[("employee", "Employee"), ("hr_manual", "HR Manual")],
                default="employee",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="source_document_ref",
            field=models.CharField(blank=True, help_text="Reference to source document for manual HR entries.", max_length=255),
        ),
    ]
