# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_leave_company(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    LeaveType = apps.get_model("leaves", "LeaveType")
    LeaveRequest = apps.get_model("leaves", "LeaveRequest")
    LeaveBalanceAdjustment = apps.get_model("leaves", "LeaveBalanceAdjustment")
    ffi = OrganizationNode.objects.get(code="FFI")
    LeaveType.objects.filter(company__isnull=True).update(company=ffi)
    LeaveRequest.objects.filter(company__isnull=True).update(company=ffi)
    LeaveBalanceAdjustment.objects.filter(company__isnull=True).update(company=ffi)


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_rename_exceptional_to_unpaid'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalanceadjustment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_balance_adjustments', to='organization.organizationnode'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='organization.organizationnode'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leave_types', to='organization.organizationnode'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, help_text='Optional code (e.g. ANNUAL, SICK)', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(backfill_leave_company, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_leave_type_company_name'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_leave_type_company_code'),
        ),
    ]
