# Generated by Django 6.0.2 on 2026-09-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0022_reconcile_legacy_hr_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='requires_ceo_approval',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='delegate_return_status',
            field=models.CharField(blank=True, help_text='Stage a request returns to once an alternative employee added after submission approves.', max_length=30),
        ),
    ]
