# Generated by Django 6.1.1 on 2026-09-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0024_allow_cross_company_leave_delegates"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualleavepaymentrequest",
            name="locked_unused_days",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="annualleavepaymentrequest",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("pay", "Pay"),
                    ("carry_forward", "Carry Forward"),
                    ("carry_forward_locked", "Carry Forward (Leave Only)"),
                ],
                default="pay",
                max_length=20,
            ),
        ),
    ]
