# Generated by Django 6.1.1 on 2026-09-24 16:40

from django.db import migrations, models


def fold_locked_into_carry_forward(apps, schema_editor):
    """``carry_forward`` is now always leave-only, so the separate locked choice is folded into it."""
    AnnualLeavePaymentRequest = apps.get_model("leaves", "AnnualLeavePaymentRequest")
    AnnualLeavePaymentRequest.objects.filter(resolution="carry_forward_locked").update(resolution="carry_forward")


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0025_annualleavepaymentrequest_locked_unused_days"),
    ]

    operations = [
        migrations.RunPython(fold_locked_into_carry_forward, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="annualleavepaymentrequest",
            name="resolution",
            field=models.CharField(
                choices=[("pay", "Pay"), ("carry_forward", "Carry Forward")],
                default="pay",
                max_length=20,
            ),
        ),
    ]
