# Generated by Django 6.1.1 on 2026-09-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0026_annualleavepaymentrequest_resolution_two_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualleavepaymentrequest",
            name="include_locked_days_in_termination_payout",
            field=models.BooleanField(default=False),
        ),
    ]
