# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_payroll_company(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    PayrollRun = apps.get_model("payroll", "PayrollRun")
    ffi = OrganizationNode.objects.get(code="FFI")
    PayrollRun.objects.filter(company__isnull=True).update(company=ffi)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('payroll', '0003_payslip_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollrun',
            name='unique_payroll_run_period',
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='organization.organizationnode'),
        ),
        migrations.RunPython(backfill_payroll_company, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_payroll_run_period'),
        ),
    ]
