# Generated by Django 6.0.2 on 2026-04-06 12:55

import employees.storage
from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_announcement_target_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF attachment for dashboard preview and email delivery.",
                null=True,
                storage=employees.storage.PrivateUploadStorage(),
                upload_to="announcement_attachments/",
                validators=[FileExtensionValidator(allowed_extensions=["pdf"])],
            ),
        ),
    ]
