# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_announcement_company(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    Announcement = apps.get_model("announcements", "Announcement")
    ffi = OrganizationNode.objects.get(code="FFI")
    Announcement.objects.filter(company__isnull=True).update(company=ffi)


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_attachment'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='organization.organizationnode'),
        ),
        migrations.RunPython(backfill_announcement_company, migrations.RunPython.noop),
    ]
