# Generated by Codex on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_announcement_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="announcement_type",
            field=models.CharField(
                choices=[("GENERAL", "General"), ("MEETING", "Meeting")],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="google_meet_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="announcement",
            name="meeting_agenda",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="meeting_duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="meeting_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="announcement",
            name="meeting_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="microsoft_teams_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="announcement",
            name="zoom_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
