# Generated by Django 6.0.2 on 2026-09-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0006_announcement_whole_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="whatsapp_group_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="AnnouncementWhatsAppGroupDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.CharField(max_length=64)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUBMITTED", "Submitted"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("UNKNOWN", "Outcome unknown"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "announcement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_group_delivery",
                        to="announcements.announcement",
                    ),
                ),
            ],
        ),
    ]
