# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_loan_company(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    LoanRequest = apps.get_model("loans", "LoanRequest")
    ffi = OrganizationNode.objects.get(code="FFI")
    LoanRequest.objects.filter(company__isnull=True).update(company=ffi)


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_type_and_installments'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='organization.organizationnode'),
        ),
        migrations.RunPython(backfill_loan_company, migrations.RunPython.noop),
    ]
