# Generated by Django 6.0.3 on 2026-04-11 22:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_employee_company(apps, schema_editor):
    OrganizationNode = apps.get_model("organization", "OrganizationNode")
    EmployeeProfile = apps.get_model("employees", "EmployeeProfile")
    ffi = OrganizationNode.objects.get(code="FFI")
    EmployeeProfile.objects.filter(company__isnull=True).update(company=ffi)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_id_prefix_to_ffi'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Owning company for this employee profile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_profiles', to='organization.organizationnode'),
        ),
        migrations.RunPython(backfill_employee_company, migrations.RunPython.noop),
    ]
