# Generated by Django 6.0.2 on 2026-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_employeedocument_deletion_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='attendance_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
