# Generated by Django 6.0.2 on 2026-09-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0026_employeedocument_ocr_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractdecision",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_HR", "Pending HR"),
                    ("PENDING_CEO", "Pending CEO"),
                    ("APPROVED", "Approved"),
                    ("AUTO_APPROVED", "Automatically approved"),
                    ("REJECTED", "Rejected"),
                    ("AUTO_RENEWED", "Automatically renewed"),
                    ("AUTO_RENEWAL_FAILED", "Automatic renewal failed"),
                    ("MANUAL_RESOLUTION_REQUIRED", "Manual resolution required"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING_HR",
                max_length=32,
            ),
        ),
    ]
