# Generated by Django 6.0.2 on 2026-09-29 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import employees.storage


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0028_employee_id_alias"),
        ("organization", "0005_organizationnode_address_organizationnode_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocumentChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(choices=[("PASSPORT", "Passport"), ("SAUDI_ID", "Saudi ID")], max_length=20),
                ),
                ("new_number", models.CharField(blank=True, max_length=50)),
                ("new_expiry", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        storage=employees.storage.PrivateUploadStorage(),
                        upload_to="employee_document_requests/",
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_HR", "Pending HR"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_HR",
                        max_length=20,
                    ),
                ),
                ("previous_number", models.CharField(blank=True, max_length=50)),
                ("previous_expiry", models.DateField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests",
                        to="employees.employeedocument",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_document_change_requests",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_change_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_change_requests",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_change_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["company", "status"], name="emp_doc_change_company_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING_HR")),
                        fields=("employee_profile", "document_type"),
                        name="emp_doc_change_one_pending",
                    )
                ],
            },
        ),
    ]
