"""Source table on pages 39-42 of the supplied executive regulations PDF.

W, O and B are the three printed sections (work time, work organization and
worker conduct). The row number is the number printed in that section. Values
are daily-wage percentages or whole daily wages, never monthly percentages.
"""

from decimal import ROUND_HALF_UP, Decimal


def _level(value):
    if value == "W":
        return {"action": "written_warning", "amount_basis": None, "amount_value": None}
    if value.startswith("P"):
        return {"action": "deduction", "amount_basis": "daily_wage_percent", "amount_value": value[1:]}
    if value.startswith("D"):
        return {"action": "deduction", "amount_basis": "daily_wage_days", "amount_value": value[1:]}
    return {"action": value, "amount_basis": None, "amount_value": None}


def _entry(section, row, page, en, ar, values, *, period=None, extra="", automatic=False):
    return {
        "code": f"{section}{row:02d}",
        "category": {"W": "work_time", "O": "work_organization", "B": "worker_conduct"}[section],
        "recurrence_group": f"{section}{row:02d}",
        "title_en": en,
        "title_ar": ar,
        "description_en": en,
        "description_ar": ar,
        "count_period": period
        or ("monthly" if section == "W" and row <= 10 else "contract_year" if section == "W" else "cumulative"),
        "levels": [{"occurrence": n, **_level(value)} for n, value in enumerate(values, 1) if value],
        "source_page": page,
        "source_row": row,
        "automatic": automatic,
        "extra_wage_deduction": extra,
    }


CATALOG = [
    # Work time, printed rows 1-10 on page 39 and 11-16 on page 40.
    _entry(
        "W",
        1,
        39,
        "Arriving up to 15 minutes late without permission or acceptable excuse, without disrupting other workers",
        "التأخر عن مواعيد الحضور للعمل لغاية 15 دقيقة دون إذن أو عذر مقبول إذا لم يترتب على ذلك تعطيل عمال آخرين",
        ["W", "P5", "P10", "P20"],
        automatic=True,
    ),
    _entry(
        "W",
        2,
        39,
        "Arriving up to 15 minutes late without permission or acceptable excuse, disrupting other workers",
        "التأخر عن مواعيد الحضور للعمل لغاية 15 دقيقة دون إذن أو عذر مقبول إذا ترتب على ذلك تعطيل عمال آخرين",
        ["W", "P15", "P25", "P50"],
        automatic=True,
    ),
    _entry(
        "W",
        3,
        39,
        "Arriving over 15 and up to 30 minutes late without permission or acceptable excuse, without disrupting other workers",
        "التأخر عن مواعيد الحضور للعمل أكثر من 15 دقيقة لغاية 30 دقيقة دون إذن أو عذر مقبول إذا لم يترتب على ذلك تعطيل عمال آخرين",
        ["P10", "P15", "P25", "P50"],
        automatic=True,
    ),
    _entry(
        "W",
        4,
        39,
        "Arriving over 15 and up to 30 minutes late without permission or acceptable excuse, disrupting other workers",
        "التأخر عن مواعيد الحضور للعمل أكثر من 15 دقيقة لغاية 30 دقيقة دون إذن أو عذر مقبول إذا ترتب على ذلك تعطيل عمال آخرين",
        ["P25", "P50", "P75", "D1"],
        automatic=True,
    ),
    _entry(
        "W",
        5,
        39,
        "Arriving over 30 and up to 60 minutes late without permission or acceptable excuse, without disrupting other workers",
        "التأخر عن مواعيد الحضور للعمل أكثر من 30 دقيقة لغاية 60 دقيقة دون إذن أو عذر مقبول إذا لم يترتب على ذلك تعطيل عمال آخرين",
        ["P25", "P50", "P75", "D1"],
        automatic=True,
    ),
    _entry(
        "W",
        6,
        39,
        "Arriving over 30 and up to 60 minutes late without permission or acceptable excuse, disrupting other workers",
        "التأخر عن مواعيد الحضور للعمل أكثر من 30 دقيقة لغاية 60 دقيقة دون إذن أو عذر مقبول إذا ترتب على ذلك تعطيل عمال آخرين",
        ["P30", "P50", "D1", "D2"],
        extra="late_minutes",
        automatic=True,
    ),
    _entry(
        "W",
        7,
        39,
        "Arriving more than 60 minutes late without permission or acceptable excuse, whether or not other workers are disrupted",
        "التأخر عن مواعيد الحضور للعمل لمدة تزيد على ساعة دون إذن أو عذر مقبول سواء ترتب أو لم يترتب على ذلك تعطيل عمال آخرين",
        ["W", "D1", "D2", "D3"],
        extra="late_hours",
        automatic=True,
    ),
    _entry(
        "W",
        8,
        39,
        "Leaving work up to 15 minutes early without permission or acceptable excuse",
        "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما لا يتجاوز 15 دقيقة",
        ["W", "P10", "P25", "D1"],
        extra="unworked_time",
        automatic=True,
    ),
    _entry(
        "W",
        9,
        39,
        "Leaving work more than 15 minutes early without permission or acceptable excuse",
        "ترك العمل أو الانصراف قبل الميعاد دون إذن أو عذر مقبول بما يتجاوز 15 دقيقة",
        ["P10", "P25", "P50", "D1"],
        extra="unworked_time",
        automatic=True,
    ),
    _entry(
        "W",
        10,
        39,
        "Remaining at or returning to the workplace after work hours without prior permission",
        "البقاء في أماكن العمل أو العودة إليها بعد انتهاء مواعيد العمل دون إذن مسبق",
        ["W", "P10", "P25", "D1"],
        automatic=True,
    ),
    _entry(
        "W",
        11,
        40,
        "Absent for one day without written permission or acceptable excuse within one contract year",
        "الغياب دون إذن كتابي أو عذر مقبول لمدة يوم خلال السنة العقدية الواحدة",
        ["P50", "D1", "D2", "D3"],
        automatic=True,
    ),
    _entry(
        "W",
        12,
        40,
        "Continuously absent for two to six days without written permission or acceptable excuse within one contract year",
        "الغياب المتصل دون إذن كتابي أو عذر مقبول من يومين إلى ستة أيام خلال السنة العقدية الواحدة",
        ["D2", "D3", "D4", "promotion_delay_or_one_allowance_denial"],
        extra="absence_period",
        automatic=True,
    ),
    _entry(
        "W",
        13,
        40,
        "Continuously absent for seven to ten days without written permission or acceptable excuse within one contract year",
        "الغياب المتصل دون إذن كتابي أو عذر مقبول من سبعة أيام إلى عشرة أيام خلال السنة العقدية الواحدة",
        ["D4", "D5", "promotion_delay_or_one_allowance_denial", "conditional_termination_with_benefit"],
        extra="absence_period",
        automatic=True,
    ),
    _entry(
        "W",
        14,
        40,
        "Continuously absent for eleven to fourteen days without written permission or acceptable excuse within one contract year",
        "الغياب المتصل دون إذن كتابي أو عذر مقبول من أحد عشر يوما إلى أربعة عشر يوما خلال السنة العقدية الواحدة",
        ["D5", "promotion_delay_or_one_allowance_denial_with_article_80_warning", "article_80_termination", None],
        extra="absence_period",
        automatic=True,
    ),
    _entry(
        "W",
        15,
        40,
        "Uninterrupted absence for more than fifteen days without a legitimate reason in one contract year; written warning after ten days required",
        "الانقطاع عن العمل دون سبب مشروع لمدة تزيد على خمسة عشر يوما متصلة خلال السنة العقدية الواحدة على أن يسبقه إنذار كتابي بعد الغياب مدة عشرة أيام",
        ["article_80_termination"],
        automatic=True,
    ),
    _entry(
        "W",
        16,
        40,
        "Intermittent absence totalling more than thirty days without a legitimate reason in one contract year; written warning after twenty days required",
        "الغياب المتقطع دون سبب مشروع مدة تزيد في مجموعها على ثلاثين يوما خلال السنة العقدية الواحدة على أن يسبقه إنذار كتابي بعد الغياب مدة عشرين يوما",
        ["article_80_termination"],
        automatic=True,
    ),
    # Work organization, printed rows 1-4 on page 40 and 5-18 on page 41.
    _entry(
        "O",
        1,
        40,
        "Being outside the assigned workplace during working hours without justification",
        "التواجد دون مبرر في غير مكان العمل المخصص للعامل أثناء وقت الدوام",
        ["P10", "P25", "P50", "D1"],
    ),
    _entry(
        "O",
        2,
        40,
        "Receiving visitors on work premises for matters unrelated to work without management permission",
        "استقبال زائرين في غير أمور عمل المنشأة في أماكن العمل دون إذن من الإدارة",
        ["W", "P10", "P15", "P25"],
    ),
    _entry(
        "O",
        3,
        40,
        "Using the establishment's machines, equipment or tools for private purposes without permission",
        "استعمال آلات ومعدات وأدوات المنشأة لأغراض خاصة دون إذن",
        ["W", "P10", "P25", "P50"],
    ),
    _entry(
        "O",
        4,
        40,
        "Interfering without authority in work outside the worker's duties",
        "تدخل العامل دون وجه حق في أي عمل ليس في اختصاصه أو لم يعهد به إليه",
        ["P50", "D1", "D2", "D3"],
    ),
    _entry(
        "O",
        5,
        41,
        "Entering or leaving through a place other than the designated entrance or exit",
        "الخروج أو الدخول من غير المكان المخصص لذلك",
        ["W", "P10", "P15", "P25"],
    ),
    _entry(
        "O",
        6,
        41,
        "Neglecting to clean, maintain or care for machinery, or failing to report a fault",
        "الإهمال في تنظيف الآلات وصيانتها أو عدم العناية بها أو عدم التبليغ عما بها من خلل",
        ["P50", "D1", "D2", "D3"],
    ),
    _entry(
        "O",
        7,
        41,
        "Failing to put repair, maintenance or other tools in their designated places after work",
        "عدم وضع أدوات الإصلاح والصيانة واللوازم الأخرى في الأماكن المخصصة لها بعد الانتهاء من العمل",
        ["W", "P25", "P50", "D1"],
    ),
    _entry(
        "O",
        8,
        41,
        "Tearing or damaging establishment notices or management announcements",
        "تمزيق أو إتلاف إعلانات أو بلاغات إدارة المنشأة",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "O",
        9,
        41,
        "Neglecting property entrusted to the worker, such as vehicles, machines, devices, equipment or tools",
        "الإهمال في العهد التي بحوزته مثل سيارات وآلات وأجهزة ومعدات وأدوات",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "O",
        10,
        41,
        "Eating in the workplace, an undesignated place, or outside rest times",
        "الأكل في مكان العمل أو غير المكان المعد له أو في غير أوقات الراحة",
        ["W", "P10", "P15", "P25"],
    ),
    _entry("O", 11, 41, "Sleeping during work", "النوم أثناء العمل", ["W", "P10", "P25", "P50"]),
    _entry(
        "O",
        12,
        41,
        "Sleeping in duties requiring constant vigilance",
        "النوم في الحالات التي تستدعي يقظة مستمرة",
        ["P50", "D1", "D2", "D3"],
    ),
    _entry(
        "O",
        13,
        41,
        "Loitering or being away from one's work location during working hours",
        "التسكع أو وجود العامل في غير مكان عمله أثناء ساعات العمل",
        ["P10", "P25", "P50", "D1"],
    ),
    _entry(
        "O",
        14,
        41,
        "Manipulating attendance or departure records",
        "التلاعب في إثبات الحضور والانصراف",
        ["D1", "D2", "promotion_delay_or_one_allowance_denial", "termination_with_benefit"],
    ),
    _entry(
        "O",
        15,
        41,
        "Disobeying ordinary work orders or posted work instructions",
        "عدم إطاعة الأوامر العادية الخاصة بالعمل أو عدم تنفيذ التعليمات الخاصة بالعمل والمعلقة في مكان ظاهر",
        ["P25", "P50", "D1", "D2"],
    ),
    _entry(
        "O",
        16,
        41,
        "Inciting violation of work orders or written work instructions",
        "التحريض على مخالفة الأوامر والتعليمات الخطية الخاصة بالعمل",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "O",
        17,
        41,
        "Smoking in prohibited places posted for worker and establishment safety",
        "التدخين في الأماكن المحظورة والمعلن عنها للمحافظة على سلامة العمال والمنشأة",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "O",
        18,
        41,
        "Negligence or carelessness at work that may harm workers' health or safety, materials, tools or equipment",
        "الإهمال أو التهاون في العمل الذي قد ينشأ عنه ضرر في صحة العمال أو سلامتهم أو في المواد أو الأدوات والأجهزة",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    # Worker conduct, printed rows 1-3 on page 41 and 4-16 on page 42.
    _entry(
        "B",
        1,
        41,
        "Quarrelling with colleagues or others, or causing disturbances at work",
        "التشاجر مع الزملاء أو مع الغير أو إحداث مشاغبات في مكان العمل",
        ["D1", "D2", "D3", "D5"],
    ),
    _entry(
        "B",
        2,
        41,
        "Feigning illness or falsely claiming an injury during or because of work",
        "التمارض أو ادعاء العامل كذبا أنه أصيب أثناء العمل أو بسببه",
        ["D1", "D2", "D3", "D5"],
    ),
    _entry(
        "B",
        3,
        41,
        "Refusing a medical examination requested by the establishment doctor or treatment instructions",
        "الامتناع عن إجراء الكشف الطبي عند طلب طبيب المنشأة أو رفض اتباع التعليمات الطبية أثناء العلاج",
        ["D1", "D2", "D3", "D5"],
    ),
    _entry(
        "B",
        4,
        42,
        "Violating posted health instructions at the workplace",
        "مخالفة التعليمات الصحية المعلقة بأماكن العمل",
        ["P50", "D1", "D2", "D5"],
    ),
    _entry(
        "B",
        5,
        42,
        "Writing on establishment walls or affixing notices to them",
        "الكتابة على جدران المنشأة أو لصق إعلانات عليها",
        ["W", "P10", "P25", "P50"],
    ),
    _entry(
        "B",
        6,
        42,
        "Refusing administrative inspection on departure",
        "رفض التفتيش الإداري عند الانصراف",
        ["P25", "P50", "D1", "D2"],
    ),
    _entry(
        "B",
        7,
        42,
        "Failing to hand over establishment collections on the specified dates without acceptable justification",
        "عدم تسليم النقود المحصلة لحساب المنشأة في المواعيد المحددة دون تبرير مقبول",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "B",
        8,
        42,
        "Refusing to wear required protective clothing or equipment",
        "الامتناع عن ارتداء الملابس والأجهزة المقررة للوقاية والسلامة",
        ["W", "D1", "D2", "D5"],
    ),
    _entry(
        "B",
        9,
        42,
        "Deliberate seclusion with a person of the opposite sex at work",
        "تعمد الخلوة مع الجنس الآخر في أماكن العمل",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "B",
        10,
        42,
        "Offending others in a way that violates decency, by speech or action",
        "الإيحاء للآخرين بما يخدش الحياء قولا أو فعلا",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "B",
        11,
        42,
        "Verbally assaulting colleagues by speech, gesture, abusive electronic communications or belittling",
        "الاعتداء على زملاء العمل بالقول أو الإشارة أو باستعمال وسائل الاتصال الإلكترونية بالشتم أو التحقير",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "B",
        12,
        42,
        "Physical assault on colleagues or others in an indecent manner",
        "الاعتداء بالإيذاء الجسدي على زملاء العمل أو على غيرهم بطريقة إباحية",
        ["termination_without_benefit_or_notice_or_compensation"],
    ),
    _entry(
        "B",
        13,
        42,
        "Physical or verbal assault or abusive electronic communications against the employer, manager or superiors",
        "الاعتداء الجسدي أو القولي أو بأي وسيلة من وسائل الاتصال الإلكترونية على صاحب العمل أو المدير المسؤول أو أحد الرؤساء أثناء العمل أو بسببه",
        ["termination_without_benefit_or_notice_or_compensation"],
    ),
    _entry(
        "B",
        14,
        42,
        "Submitting a malicious report or complaint",
        "تقديم بلاغ أو شكوى كيدية",
        ["D3", "D5", "termination_with_benefit", None],
    ),
    _entry(
        "B",
        15,
        42,
        "Failing to comply with an investigation committee's request to attend",
        "عدم الامتثال لطلب لجنة التحقيق بالحضور",
        ["D2", "D3", "D5", "termination_with_benefit"],
    ),
    _entry(
        "B",
        16,
        42,
        "Failing to observe the establishment's approved official uniform",
        "عدم التقيد بالزي الرسمي المعتمد بالمنشأة",
        ["D1", "D2", "D3", "D5"],
    ),
]


def monetary_amount(profile, level):
    basis = level.get("amount_basis")
    value = Decimal(level["amount_value"]) if level.get("amount_value") else Decimal("0")
    daily = (profile.total_salary or Decimal("0")) / Decimal("30")
    if basis == "daily_wage_percent":
        return (daily * value / Decimal("100")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    if basis == "daily_wage_days":
        return (daily * value).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    return Decimal("0.00")
