# Generated by Django 6.1.1 on 2026-09-16 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0026_employeedocument_ocr_review"),
        ("organization", "0005_organizationnode_address_organizationnode_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_RESPONSES", "Awaiting both responses"),
                            ("WAITING_MANAGER", "Awaiting manager response"),
                            ("WAITING_EMPLOYEE", "Awaiting employee response"),
                            ("PENDING_HR", "Pending HR review"),
                            ("PENDING_CEO", "Pending CEO approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("MANUAL_RESOLUTION_REQUIRED", "Manual resolution required"),
                        ],
                        db_index=True,
                        default="PENDING_RESPONSES",
                        max_length=32,
                    ),
                ),
                ("department_snapshot", models.CharField(blank=True, max_length=255)),
                ("section_snapshot", models.CharField(blank=True, max_length=255)),
                ("job_title_snapshot", models.CharField(blank=True, max_length=255)),
                ("evaluation_period_from", models.DateField(blank=True, null=True)),
                ("evaluation_period_to", models.DateField(blank=True, null=True)),
                ("comparison_summary", models.JSONField(blank=True, default=dict)),
                ("hr_comment", models.TextField(blank=True)),
                ("hr_decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ceo_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCEPT", "Accept"),
                            ("RETURN_TO_HR", "Return to HR"),
                            ("DECLINE", "Decline"),
                            ("DECLINE_WITH_ALTERNATIVE", "Decline and select alternative"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "ceo_selected_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RENEW", "Renew"),
                            ("RENEW_WITH_CHANGES", "Renew with changes"),
                            ("TERMINATE", "Terminate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ceo_comment", models.TextField(blank=True)),
                ("ceo_decided_at", models.DateTimeField(blank=True, null=True)),
                ("salary_change_proposed", models.BooleanField(default=False)),
                ("salary_before_snapshot", models.JSONField(blank=True, default=dict)),
                ("ceo_approved_terms", models.JSONField(blank=True, default=dict)),
                ("ceo_salary_override_reason", models.TextField(blank=True)),
                ("salary_effective_date", models.DateField(blank=True, null=True)),
                ("salary_change_applied_at", models.DateTimeField(blank=True, null=True)),
                ("salary_after_snapshot", models.JSONField(blank=True, default=dict)),
                ("scheduled_termination", models.BooleanField(default=False)),
                ("employee_notified_of_termination_at", models.DateTimeField(blank=True, null=True)),
                ("termination_processed_at", models.DateTimeField(blank=True, null=True)),
                ("notification_milestones", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ceo_decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_ratings",
                        to="organization.organizationnode",
                    ),
                ),
                (
                    "contract_decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rating",
                        to="employees.contractdecision",
                    ),
                ),
                (
                    "employee_notified_of_termination_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_ratings",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "hr_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager_at_creation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractRatingResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rater_type",
                    models.CharField(choices=[("MANAGER", "Manager"), ("EMPLOYEE", "Employee")], max_length=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUBMITTED", "Submitted"), ("RETURNED", "Returned for correction")],
                        default="SUBMITTED",
                        max_length=10,
                    ),
                ),
                ("criterion_ratings", models.JSONField(default=dict)),
                ("average_score", models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                (
                    "overall_grade",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("VERY_GOOD", "Very Good"),
                            ("GOOD", "Good"),
                            ("ACCEPTABLE", "Acceptable"),
                            ("POOR", "Poor"),
                        ],
                        editable=False,
                        max_length=32,
                    ),
                ),
                ("overall_remark", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONTINUE_CONTRACT", "Continue the contract"),
                            ("CONTINUE_WITH_CHANGES", "Continue with changes"),
                            ("TERMINATE", "Terminate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("recommended_change_types", models.JSONField(blank=True, default=list)),
                ("proposed_terms", models.JSONField(blank=True, default=dict)),
                ("proposed_job_title", models.CharField(blank=True, max_length=100)),
                ("proposed_position_id", models.IntegerField(blank=True, null=True)),
                ("other_change_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("return_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="contract_ratings.contractrating",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contractrating",
            name="employee_response",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contract_ratings.contractratingresponse",
            ),
        ),
        migrations.AddField(
            model_name="contractrating",
            name="manager_response",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contract_ratings.contractratingresponse",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractratingresponse",
            constraint=models.UniqueConstraint(
                fields=("rating", "rater_type"), name="one_response_per_rater_per_cycle"
            ),
        ),
        migrations.AddIndex(
            model_name="contractrating",
            index=models.Index(fields=["company", "status"], name="contract_ra_company_4ed934_idx"),
        ),
    ]
