# Generated by Django 6.0.2 on 2026-09-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contract_ratings", "0003_hr_rating_gate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractrating",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_HR_GATE", "Awaiting HR: rate or send to CEO"),
                    ("PENDING_RESPONSES", "Awaiting both responses"),
                    ("WAITING_MANAGER", "Awaiting manager response"),
                    ("WAITING_EMPLOYEE", "Awaiting employee response"),
                    ("PENDING_CEO", "Pending CEO decision"),
                    ("DECIDED", "Decided"),
                    ("MANUAL_RESOLUTION_REQUIRED", "Manual resolution required"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING_HR_GATE",
                max_length=32,
            ),
        ),
    ]
