# Generated by Django 6.0.3 on 2026-03-12 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('module_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module_key', 'key'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('current_stage', models.CharField(blank=True, default='', max_length=100)),
                ('current_approver_role', models.CharField(blank=True, default='', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('current_actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_assignments', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='core.workflowdefinition')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Cancel'), ('advance', 'Advance'), ('reassign', 'Reassign'), ('skip', 'Skip'), ('override', 'Override'), ('disburse', 'Disburse'), ('deduct', 'Deduct')], max_length=20)),
                ('approver_role', models.CharField(blank=True, default='', max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('from_stage', models.CharField(blank=True, default='', max_length=100)),
                ('to_stage', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.workflowinstance')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('approver_role', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveSmallIntegerField()),
                ('is_optional', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('condition_key', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.workflowdefinition')),
            ],
            options={
                'ordering': ['definition_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DelegationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_rules_created', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['from_user', 'is_active'], name='core_del_from_act_idx'), models.Index(fields=['to_user', 'is_active'], name='core_del_to_act_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'current_approver_role'], name='core_wfins_stat_role_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='core_wfins_obj_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='core_wfinstance_unique_object'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['workflow', 'created_at'], name='core_wfact_wf_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['action'], name='core_wfact_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstagedefinition',
            constraint=models.UniqueConstraint(fields=('definition', 'key'), name='core_wfstage_unique_definition_key'),
        ),
        migrations.AddConstraint(
            model_name='workflowstagedefinition',
            constraint=models.UniqueConstraint(fields=('definition', 'order'), name='core_wfstage_unique_definition_order'),
        ),
    ]
