# Generated by Django 6.0.2 on 2026-08-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_scope_membership_and_delegation_lifecycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "Submit"),
                    ("approve", "Approve"),
                    ("request_changes", "Request Changes"),
                    ("reject", "Reject"),
                    ("cancel", "Cancel"),
                    ("advance", "Advance"),
                    ("reassign", "Reassign"),
                    ("skip", "Skip"),
                    ("override", "Override"),
                    ("disburse", "Disburse"),
                    ("deduct", "Deduct"),
                ],
                max_length=20,
            ),
        ),
    ]
