# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="channel",
            field=models.CharField(
                choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                default="email",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
