# Generated by Codex on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invites", "0002_invite_channel_phone_number_and_nullable_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="last_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="last_delivery_channel",
            field=models.CharField(blank=True, choices=[("email", "Email"), ("whatsapp", "WhatsApp")], max_length=16),
        ),
        migrations.AddField(
            model_name="invite",
            name="last_delivery_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="invite",
            name="last_delivery_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="invite",
            name="last_delivery_provider",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invite",
            name="last_delivery_sent",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="last_delivery_status_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
